#!/usr/bin/env bash

# Geoptimaliseerde Ventura VM met:
# - 16GB RAM (was 8GB)
# - 8 cores / 16 threads (was 4/8)
# - VirtIO disk (sneller dan IDE)
# - CPU pinning voor betere prestaties
# - Hugepages support

MY_OPTIONS="+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check"

ALLOCATED_RAM="16384" # 16GB
CPU_SOCKETS="1"
CPU_CORES="8"
CPU_THREADS="16"

REPO_PATH="."
OVMF_DIR="."

args=(
  -enable-kvm -m "$ALLOCATED_RAM" -cpu Penryn,kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,"$MY_OPTIONS"
  -machine q35,accel=kvm,kernel_irqchip=on
  -usb
  -device usb-kbd
  -device usb-tablet
  -smp "$CPU_THREADS",cores="$CPU_CORES",sockets="$CPU_SOCKETS"
  -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
  -drive if=pflash,format=raw,readonly=on,file="$REPO_PATH/$OVMF_DIR/OVMF_CODE.fd"
  -drive if=pflash,format=raw,file="$REPO_PATH/$OVMF_DIR/OVMF_VARS-Ventura.fd"
  -smbios type=2
  -device ich9-intel-hda -device hda-duplex
  -device ich9-ahci,id=sata
  # OpenCore blijft op IDE (snapshot mode)
  -drive id=OpenCoreBoot,if=none,snapshot=on,format=qcow2,file="$REPO_PATH/OpenCore/OpenCore.qcow2"
  -device ide-hd,bus=sata.2,drive=OpenCoreBoot
  # macOS disk op VirtIO voor max snelheid
  -drive id=MacHDD,if=none,file="$REPO_PATH/mac_hdd_ventura.img",format=qcow2,cache=writeback,aio=threads
  -device virtio-blk-pci,drive=MacHDD
  -netdev user,id=net0,hostfwd=tcp::2223-:22 -device virtio-net-pci,netdev=net0,id=net0,mac=52:54:00:c9:18:28
  -device vmware-svga
  -display gtk,grab-on-hover=on
  # Memory optimalisaties
  -mem-prealloc
  -overcommit mem-lock=off
)

qemu-system-x86_64 "${args[@]}"
