#!/usr/bin/env bash

MY_OPTIONS="+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check"

ALLOCATED_RAM="8192" # MiB
CPU_SOCKETS="1"
CPU_CORES="4"
CPU_THREADS="8"

REPO_PATH="."
OVMF_DIR="."

args=(
  -enable-kvm -m "$ALLOCATED_RAM" -cpu Penryn,kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,"$MY_OPTIONS"
  -machine q35
  -usb
  -device usb-kbd
  -device usb-tablet
  -smp "$CPU_THREADS",cores="$CPU_CORES",sockets="$CPU_SOCKETS"
  -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
  -drive if=pflash,format=raw,readonly=on,file="$REPO_PATH/$OVMF_DIR/OVMF_CODE.fd"
  -drive if=pflash,format=raw,file="$REPO_PATH/$OVMF_DIR/OVMF_VARS-Ventura.fd"
  -smbios type=2
  -device ich9-intel-hda -device hda-duplex
  -device ich9-ahci,id=sata
  -drive id=OpenCoreBoot,if=none,snapshot=on,format=qcow2,file="$REPO_PATH/OpenCore/OpenCore.qcow2"
  -device ide-hd,bus=sata.2,drive=OpenCoreBoot
  -device ide-hd,bus=sata.3,drive=InstallMedia
  -drive id=InstallMedia,if=none,file="$REPO_PATH/Ventura-Installer.img",format=raw
  -drive id=MacHDD,if=none,file="$REPO_PATH/mac_hdd_ventura.img",format=qcow2
  -device ide-hd,bus=sata.4,drive=MacHDD
  -drive id=SharedSupport,if=none,file="$REPO_PATH/SharedSupport.img",format=raw
  -device ide-hd,bus=sata.5,drive=SharedSupport
  -netdev user,id=net0,net=192.168.100.0/24,dhcpstart=192.168.100.10,dns=8.8.8.8,hostfwd=tcp::2223-:22 -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:28
  -device vmware-svga
  -display gtk,grab-on-hover=on
)

qemu-system-x86_64 "${args[@]}"
