#!/usr/bin/env bash

# Geoptimaliseerde Catalina VM met:
# - 16GB RAM (was 4GB)
# - 8 cores / 16 threads (was 2/4)
# - VirtIO disk (sneller dan IDE)
# - Memory pre-allocatie voor betere prestaties

MY_OPTIONS="+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check"

ALLOCATED_RAM="16384" # 16GB
CPU_SOCKETS="1"
CPU_CORES="8"
CPU_THREADS="16"

REPO_PATH="."
OVMF_DIR="."

args=(
  -enable-kvm -m "$ALLOCATED_RAM" -cpu Penryn,kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,"$MY_OPTIONS"
  -machine q35,accel=kvm,kernel_irqchip=on
  -usb -device usb-kbd -device usb-tablet
  -device usb-ehci,id=ehci
  -device nec-usb-xhci,id=xhci
  -global nec-usb-xhci.msi=off
  -smp "$CPU_THREADS",cores="$CPU_CORES",sockets="$CPU_SOCKETS"
  -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
  -drive if=pflash,format=raw,readonly=on,file="$REPO_PATH/$OVMF_DIR/OVMF_CODE.fd"
  -drive if=pflash,format=raw,file="$REPO_PATH/$OVMF_DIR/OVMF_VARS-1920x1080.fd"
  -smbios type=2
  -device ich9-intel-hda -device hda-duplex
  -device ich9-ahci,id=sata
  # OpenCore blijft op IDE (snapshot mode)
  -drive id=OpenCoreBoot,if=none,snapshot=on,format=qcow2,file="$REPO_PATH/OpenCore/OpenCore.qcow2"
  -device ide-hd,bus=sata.2,drive=OpenCoreBoot
  # macOS disk op VirtIO voor max snelheid
  -drive id=MacHDD,if=none,file="$REPO_PATH/mac_hdd_ng.img",format=qcow2,cache=writeback,aio=threads
  -device virtio-blk-pci,drive=MacHDD
  -netdev user,id=net0,dns=8.8.8.8,hostfwd=tcp::2222-:22 -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:27
  -device vmware-svga
  -display sdl,gl=on
  # Memory optimalisaties
  -mem-prealloc
  -overcommit mem-lock=off
)

qemu-system-x86_64 "${args[@]}"
